### PR TITLE
hang_processes.sh: Obtain list of loaded dynamic objects using strings

### PR DESCRIPTION
**Pull request by simark**
While this is quite ugly, it has the advantage that we get the path to
the object files actually loaded by the application.  So if it loaded
some particular shared object due due to some LD_LIBRARY_PATH value or
because it dlopen'ed them, we will catch them.

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>

### CODE REVIEW

**Comment by simark** [comment]
Ok, this is (probably) ready to be reviewed.

**Comment by PSRCode** [comment]
Looks good. I'm not a big fan of read while loop but this is a matter of taste (even if it is a bit "safer" too if I remember correctly). This script is short enough that  I don't mind.

Thanks

**Comment by PSRCode** [comment]
This is deployed, let's see how it behave in the wild.

**Comment by simark** [comment]
> Looks good. I'm not a big fan of read while loop but this is a matter of taste (even if it is a bit "safer" too if I remember correctly). This script is short enough that I don't mind.

Yeah, this is to handle correctly filenames with spaces.  For the "for each core file" loop, we know there won't be spaces, so if you want I can change it to use "for ... in".  For the "strings" loop, it's not very likely, but we never know, there could be a path with a space in it...

**Pull request merged**
