### PR TITLE
Fix failing git clone in Lava jobs

### PR DESCRIPTION
**Pull request by frdeso**

### CODE REVIEW

**Comment by mjeanson** [comment]
Is it possible to use something like ''mktemp -d'' to create a temporary directory instead of using a static path?

**Comment by frdeso** [comment]
I moved the repository checkout out of the test description to allow for a temporary directory to be used as the clone target directory.

**Comment by mjeanson** [comment]
Is there a side effect of removing the benchmark repo from the git-repos section?

**Comment by frdeso** [comment]
I don't think so. It now does the clone during the test steps instead of during the bootstrap. I am not 100% sure on that there is no side effect.

**Comment by mjeanson** [comment]
We'll see.

**Pull request merged**
