### PR TITLE
jjb: system-tests: remove baremetal benchmarks

### PR DESCRIPTION
**Pull request by frdeso**
We currently don't have the bandwidth to track those results and
investigate bugs in the benchmarks themselves. We could always revert
this commit if that changes.

Right now, these benchmarks are only wasting CI CPU time and power.

Signed-off-by: Francis Deslauriers <fdeslaur@gmail.com>

### CODE REVIEW

**Comment by mjeanson** [comment]
I'm OK with this, Jonathan?

**Comment by PSRCode** [comment]
LGTM, I'll use jjb to delete the jobs.

Thanks

**Comment by PSRCode** [comment]
The jobs were deleted, can you please do a simple checkup to make sure I did not miss anything?

I used 
```
jenkins-jobs --conf etc/jenkins_jobs.ini list jobs/system-tests.yaml 'baremetal_benchmarks_k*'
```

On the previous commit to get the list of jobs, then used the following to delete them:
```
jenkins-jobs --conf etc/jenkins_jobs.ini delete baremetal_benchmarks_kcanary_lcanary baremetal_benchmarks_kcanary_lmaster baremetal_benchmarks_kcanary_lstable-2.10 baremetal_benchmarks_kcanary_lstable-2.11 baremetal_benchmarks_kcanary_lstable-2.12 baremetal_benchmarks_klinux-4.14.y_lcanary baremetal_benchmarks_klinux-4.14.y_lmaster baremetal_benchmarks_klinux-4.14.y_lstable-2.10 baremetal_benchmarks_klinux-4.14.y_lstable-2.11 baremetal_benchmarks_klinux-4.14.y_lstable-2.12 baremetal_benchmarks_klinux-4.19.y_lcanary baremetal_benchmarks_klinux-4.19.y_lmaster baremetal_benchmarks_klinux-4.19.y_lstable-2.10 baremetal_benchmarks_klinux-4.19.y_lstable-2.11 baremetal_benchmarks_klinux-4.19.y_lstable-2.12 baremetal_benchmarks_klinux-4.4.y_lcanary baremetal_benchmarks_klinux-4.4.y_lmaster baremetal_benchmarks_klinux-4.4.y_lstable-2.10 baremetal_benchmarks_klinux-4.4.y_lstable-2.11 baremetal_benchmarks_klinux-4.4.y_lstable-2.12 baremetal_benchmarks_klinux-4.9.y_lcanary baremetal_benchmarks_klinux-4.9.y_lmaster baremetal_benchmarks_klinux-4.9.y_lstable-2.10 baremetal_benchmarks_klinux-4.9.y_lstable-2.11 baremetal_benchmarks_klinux-4.9.y_lstable-2.12 baremetal_benchmarks_klinux-5.0.y_lcanary baremetal_benchmarks_klinux-5.0.y_lmaster baremetal_benchmarks_klinux-5.0.y_lstable-2.10 baremetal_benchmarks_klinux-5.0.y_lstable-2.11 baremetal_benchmarks_klinux-5.0.y_lstable-2.12 baremetal_benchmarks_klinux-5.1.y_lcanary baremetal_benchmarks_klinux-5.1.y_lmaster baremetal_benchmarks_klinux-5.1.y_lstable-2.10 baremetal_benchmarks_klinux-5.1.y_lstable-2.11 baremetal_benchmarks_klinux-5.1.y_lstable-2.12 baremetal_benchmarks_klinux-5.4.y_lcanary baremetal_benchmarks_klinux-5.4.y_lmaster baremetal_benchmarks_klinux-5.4.y_lstable-2.10 baremetal_benchmarks_klinux-5.4.y_lstable-2.11 baremetal_benchmarks_klinux-5.4.y_lstable-2.12 baremetal_benchmarks_kmaster_lcanary baremetal_benchmarks_kmaster_lmaster baremetal_benchmarks_kmaster_lstable-2.11 baremetal_benchmarks_kmaster_lstable-2.12
```

**Comment by mjeanson** [comment]
LGTM

**Pull request merged**
